### ISSUE TITLE
Feature : Add accessibility features

### ISSUE THREAD

**Issue by ShubhamHande99** [ShubhamHande99/flutter_accessibility#3]
## Feature: Add accessibility features

**Description:**
Add accessibility features

**Tasks:**
- [x] tooltip for icons
- [x] Semantics label for widgets
- [x] Responsive font size
- [x] Ensure no overflow issue when text size or display size in increased
- [x] Handle conditional state changes messages for Android TalkBack and IOS VoiceOver
- [x] custom onTapHint message such "double tap to view product details" instead of default message "double tap to activate"

**Comment by ShubhamHande99** [comment]
Completed the feature.
* #4
